[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
	ignore:.*asyncio.get_event_loop_policy.*:DeprecationWarning:pytest_asyncio.plugin
	ignore:.*asyncio.set_event_loop_policy.*:DeprecationWarning:pytest_asyncio.plugin
